apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: utils
type: Opaque
data:
  username: dXNlcg==       # "user" codificado en base64
  password: QWJjLi4xMjM    # "Abc..123" codificado en base64
